import { db } from "@workspace/db";
import { productsTable, categoriesTable, liveEventsTable, liveFeedTable } from "@workspace/db/schema";

const categories = [
  { name: "Dresses", slug: "dresses", imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80", productCount: 0 },
  { name: "Heels & Shoes", slug: "heels-shoes", imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80", productCount: 0 },
  { name: "Tops & Blouses", slug: "tops-blouses", imageUrl: "https://images.unsplash.com/photo-1597528380307-4b759c06dda3?w=400&q=80", productCount: 0 },
  { name: "Lingerie", slug: "lingerie", imageUrl: "https://images.unsplash.com/photo-1554568218-0f1715e72254?w=400&q=80", productCount: 0 },
  { name: "Accessories", slug: "accessories", imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80", productCount: 0 },
  { name: "Skirts & Pants", slug: "skirts-pants", imageUrl: "https://images.unsplash.com/photo-1587370560942-ad2a04eabb6d?w=400&q=80", productCount: 0 },
];

const products = [
  {
    name: "Femme Fatale Sequin Dress",
    description: "Turn every room into your runway. This floor-length sequin gown catches light like a prism — made for bodies of all shapes. Fully inclusive sizing, trans and curvy-affirming fit.",
    price: "289.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80", "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80"],
    category: "dresses",
    tags: ["sequin", "gown", "evening", "featured"],
    sizes: ["XS", "S", "M", "L", "XL", "2X", "3X"],
    colors: ["Black", "Gold", "Ruby Red"],
    inStock: true,
    stockCount: 15,
    rating: "4.90",
    reviewCount: 127,
    isFeatured: true,
    isNew: false,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Siren Wrap Mini Dress",
    description: "Wrap yourself in confidence. This satin-touch mini wraps perfectly around every curve. Adjustable tie means it fits every body beautifully — designed with trans women in mind.",
    price: "129.00",
    originalPrice: "179.00",
    imageUrl: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&q=80"],
    category: "dresses",
    tags: ["mini", "wrap", "satin", "sale"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blush Pink", "Black", "Cherry Red"],
    inStock: true,
    stockCount: 22,
    rating: "4.70",
    reviewCount: 89,
    isFeatured: true,
    isNew: false,
    isSale: true,
    lgbtqFriendly: true,
  },
  {
    name: "Goddess Platform Heels",
    description: "Walk like divinity. These 5-inch platforms come in extended sizes up to size 14 — because everyone deserves to feel elevated. Anti-slip sole, padded insole.",
    price: "189.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80"],
    category: "heels-shoes",
    tags: ["platform", "heels", "extended-sizes"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14"],
    colors: ["Black", "Nude", "Hot Pink", "Red"],
    inStock: true,
    stockCount: 30,
    rating: "4.80",
    reviewCount: 203,
    isFeatured: true,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Ethereal Lace Bodysuit",
    description: "Pure femininity. This delicate lace bodysuit features adjustable straps and a flattering cut. Designed for trans women with longer torsos. Available in nude tones for all skin tones.",
    price: "89.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1576672843344-f01907a9d40c?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1576672843344-f01907a9d40c?w=600&q=80"],
    category: "lingerie",
    tags: ["lace", "bodysuit", "lingerie"],
    sizes: ["S", "M", "L", "XL", "2X"],
    colors: ["Ivory", "Black", "Mocha", "Rose"],
    inStock: true,
    stockCount: 45,
    rating: "4.60",
    reviewCount: 56,
    isFeatured: false,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Drama Queen Corset Top",
    description: "Own the drama. Steel-boned corset top with front lace-up detail. Waist-cinching perfection — makes every silhouette more hourglass. Sizes XS-4X.",
    price: "159.00",
    originalPrice: "219.00",
    imageUrl: "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=600&q=80"],
    category: "tops-blouses",
    tags: ["corset", "waist-cinching", "sale"],
    sizes: ["XS", "S", "M", "L", "XL", "2X", "3X", "4X"],
    colors: ["Black", "Red", "Champagne"],
    inStock: true,
    stockCount: 18,
    rating: "4.85",
    reviewCount: 174,
    isFeatured: true,
    isNew: false,
    isSale: true,
    lgbtqFriendly: true,
  },
  {
    name: "Trans Pride Pearl Necklace",
    description: "Wear your pride, subtly. A stunning freshwater pearl necklace with a tiny hidden trans pride charm. Timeless elegance meets identity. Gold plated, hypoallergenic.",
    price: "69.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80"],
    category: "accessories",
    tags: ["pearl", "pride", "necklace", "trans"],
    sizes: ["One Size"],
    colors: ["Gold", "Silver"],
    inStock: true,
    stockCount: 60,
    rating: "4.95",
    reviewCount: 312,
    isFeatured: true,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Midnight Velvet Skirt",
    description: "Luxurious stretch velvet midi skirt with a flirty slit. The deep midnight blue catches light beautifully. Elastic waistband — one size fits many.",
    price: "109.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1590954651713-35a2a0c2d736?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1590954651713-35a2a0c2d736?w=600&q=80"],
    category: "skirts-pants",
    tags: ["velvet", "midi", "skirt"],
    sizes: ["XS-S", "M-L", "XL-2X"],
    colors: ["Midnight Blue", "Black", "Burgundy"],
    inStock: true,
    stockCount: 25,
    rating: "4.70",
    reviewCount: 98,
    isFeatured: false,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Red Lip Rhinestone Earrings",
    description: "Drop earrings with cascading rhinestones. The kind of earrings that make people ask about you. Lightweight despite the drama. Surgical steel posts.",
    price: "49.00",
    originalPrice: "79.00",
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80"],
    category: "accessories",
    tags: ["rhinestone", "earrings", "drop", "sale"],
    sizes: ["One Size"],
    colors: ["Crystal Clear", "Ruby", "Sapphire", "Gold"],
    inStock: true,
    stockCount: 80,
    rating: "4.80",
    reviewCount: 245,
    isFeatured: false,
    isNew: false,
    isSale: true,
    lgbtqFriendly: true,
  },
  {
    name: "Fire Goddess Bodycon Dress",
    description: "Inspired by the hero herself. Fire-red bodycon dress with asymmetric cut and ruched sides. Sculpting fabric that moves with you. Sizes XS to 3X.",
    price: "199.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80"],
    category: "dresses",
    tags: ["bodycon", "red", "asymmetric", "featured"],
    sizes: ["XS", "S", "M", "L", "XL", "2X", "3X"],
    colors: ["Crimson Red", "Black", "Orange Flame"],
    inStock: true,
    stockCount: 12,
    rating: "4.92",
    reviewCount: 89,
    isFeatured: true,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Silk Touch Blouse",
    description: "Effortlessly chic. This satin-finish blouse drapes beautifully and tucks perfectly. Long sleeves with delicate ruffle cuffs. Designed for all bodies.",
    price: "95.00",
    originalPrice: "135.00",
    imageUrl: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&q=80"],
    category: "tops-blouses",
    tags: ["silk", "blouse", "elegant", "sale"],
    sizes: ["XS", "S", "M", "L", "XL", "2X"],
    colors: ["Ivory", "Black", "Dusty Rose"],
    inStock: true,
    stockCount: 33,
    rating: "4.65",
    reviewCount: 67,
    isFeatured: false,
    isNew: false,
    isSale: true,
    lgbtqFriendly: true,
  },
  {
    name: "Glitter Ankle Boot",
    description: "Step into the spotlight. These chunky-heel glitter ankle boots come in sizes 5-14. Non-slip platform sole, side zip for easy entry. You'll never want to take them off.",
    price: "215.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80"],
    category: "heels-shoes",
    tags: ["boots", "glitter", "ankle", "extended-sizes"],
    sizes: ["5", "6", "7", "8", "9", "10", "11", "12", "13", "14"],
    colors: ["Gold Glitter", "Silver Glitter", "Black Glitter"],
    inStock: true,
    stockCount: 20,
    rating: "4.88",
    reviewCount: 156,
    isFeatured: true,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
  {
    name: "Rainbow Pride Crop Top",
    description: "Because pride isn't just in June. This fitted crop top with subtle rainbow stripe detail is made from soft breathable cotton. Perfect for layering or wearing solo.",
    price: "55.00",
    originalPrice: null,
    imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80"],
    category: "tops-blouses",
    tags: ["pride", "crop", "rainbow", "casual"],
    sizes: ["XS", "S", "M", "L", "XL", "2X", "3X"],
    colors: ["White", "Black"],
    inStock: true,
    stockCount: 55,
    rating: "4.75",
    reviewCount: 143,
    isFeatured: false,
    isNew: true,
    isSale: false,
    lgbtqFriendly: true,
  },
];

const now = new Date();
const liveEvent = {
  title: "LIVE: New Season Drop — The Dolls Runway Show",
  description: "Join host Valentina Luxe for our biggest drop of the season. Exclusive discounts, live styling tips, and first access to new arrivals — only during the stream!",
  startsAt: new Date(now.getTime() - 30 * 60 * 1000),
  endsAt: new Date(now.getTime() + 90 * 60 * 1000),
  isLive: true,
  viewerCount: 1847,
  thumbnailUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&q=80",
  hostName: "Valentina Luxe",
  featuredProducts: [1, 3, 5, 9],
};

const upcomingEvent = {
  title: "Upcoming: Summer Femme Edit",
  description: "The ultimate summer edit for femmes everywhere. New arrivals, live Q&A, and exclusive bundle deals.",
  startsAt: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000),
  endsAt: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000),
  isLive: false,
  viewerCount: 0,
  thumbnailUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&q=80",
  hostName: "Celeste Dreams",
  featuredProducts: [],
};

const feedMessages = [
  { username: "trans_goddess_nyc", message: "omg I need that sequin dress NOW", type: "chat" },
  { username: "femme4ever", message: "just ordered the platform heels! so excited", type: "purchase" },
  { username: "glitterqueen99", message: "valentina is serving LOOKS tonight", type: "chat" },
  { username: "pinknails2024", message: "just joined the stream!", type: "join" },
  { username: "makeup_maven", message: "the corset is EVERYTHING", type: "chat" },
  { username: "divakween", message: "bought the wrap dress! code DOLLS10 still works!", type: "purchase" },
  { username: "trans_joy_official", message: "this brand always makes me feel so seen", type: "chat" },
  { username: "sparkle_and_shine", message: "just joined the stream!", type: "join" },
  { username: "heels_always", message: "size 12 in stock?? asking for myself", type: "chat" },
  { username: "boldandbold", message: "just put the bodycon dress in my cart", type: "purchase" },
];

async function seed() {
  console.log("Seeding categories...");
  await db.delete(categoriesTable);
  await db.insert(categoriesTable).values(categories);

  console.log("Seeding products...");
  await db.delete(productsTable);
  await db.insert(productsTable).values(products);

  console.log("Seeding live events...");
  await db.delete(liveFeedTable);
  await db.delete(liveEventsTable);

  const [insertedEvent] = await db.insert(liveEventsTable).values(liveEvent).returning();
  await db.insert(liveEventsTable).values(upcomingEvent);

  console.log("Seeding live feed...");
  const feedWithEventId = feedMessages.map((msg, i) => ({
    ...msg,
    eventId: insertedEvent.id,
    createdAt: new Date(now.getTime() - (feedMessages.length - i) * 30 * 1000),
  }));
  await db.insert(liveFeedTable).values(feedWithEventId);

  console.log("Done seeding!");
}

seed().catch(console.error);
