uploads = []
outputs = []

[[generated]]
id = "rbcbjp3RTtd0E61gUj4Ku"
uri = "file://artifacts/the-dolls/src/assets/category-dress.png"
type = "image"
title = "Category Dress"

[[generated]]
id = "3HnrWkITrvZaaDVA8h8Qs"
uri = "file://artifacts/the-dolls/src/assets/category-heels.png"
type = "image"
title = "Category Heels"

[[generated]]
id = "sRL5EUSvYbt-RBB9q9BKa"
uri = "file://artifacts/the-dolls/src/assets/category-accessories.png"
type = "image"
title = "Category Accessories"

[[generated]]
id = "rALU347gOucDUsOX-X-4L"
uri = "file://artifacts/the-dolls/src/assets/category-makeup.png"
type = "image"
title = "Category Makeup"

[[generated]]
id = "YDxbudH1SW6cYdFGXDNJ2"
uri = "file://artifacts/the-dolls/src/assets/product-boots.png"
type = "image"
title = "Product Boots"

[[generated]]
id = "bhXIQWSIgFb-_DXCIYSKO"
uri = "file://artifacts/the-dolls/src/assets/product-top.png"
type = "image"
title = "Product Top"

[[generated]]
id = "aLYQ59NlWApJUz5cqPjly"
uri = "file://artifacts/the-dolls/src/assets/live-event-1.png"
type = "image"
title = "Live Event 1"

[[generated]]
id = "4drTcaq2pyrF_lNILeYbL"
uri = "file://artifacts/the-dolls/src/assets/live-event-2.png"
type = "image"
title = "Live Event 2"
